const artDetails = [
  {
    visible: true,
    image: "https://f4.bcbits.com/img/a3796973789_10.jpg",
    title: "Fateless",
    tagline: "The Garden is gone forever.",
    linkPrimary: "",
  },
  {
    visible: true,
    image: "https://f4.bcbits.com/img/a3796973789_10.jpg",
    title: "VESSEL: Faceless Eternities",
    tagline: "Your fate is sealed.",
    linkPrimary: "",
  },
  {
    visible: true,
    image: "https://f4.bcbits.com/img/a3796973789_10.jpg",
    title: "The Flesh of Fallen Angels",
    tagline: "Nothing is sacred.",
    linkPrimary: "",
  },
  {
    visible: true,
    image: "https://f4.bcbits.com/img/a3796973789_10.jpg",
    title: "Isn't Life Disappointing?",
    tagline: "Immeasurable pain.",
    linkPrimary: "",
  },
  {
    visible: true,
    image: "https://f4.bcbits.com/img/a3796973789_10.jpg",
    title: "S U F F E R",
    tagline: "Do you have any regrets?",
    linkPrimary: "",
  },
  {
    visible: true,
    image: "https://f4.bcbits.com/img/a3796973789_10.jpg",
    title: "SOUL: A Voiceless Decay",
    tagline: "The fear of death.",
    linkPrimary: "",
  },
  {
    visible: true,
    image: "https://f4.bcbits.com/img/a3796973789_10.jpg",
    title: "I Want to Blow My Brains Out",
    tagline: "Pull the trigger.",
    linkPrimary: "",
  },
  {
    visible: true,
    image: "https://f4.bcbits.com/img/a3796973789_10.jpg",
    title: "She Is All Yours",
    tagline: "Do what you want. Are you satisfied?",
    linkPrimary: "",
  },
  {
    visible: true,
    image: "https://f4.bcbits.com/img/a3796973789_10.jpg",
    title: "There is a dark voice inside my mind.",
    tagline: "Something personal.",
    linkPrimary: "",
  },
  {
    visible: true,
    image: "https://f4.bcbits.com/img/a3796973789_10.jpg",
    title: "SKIN",
    tagline: "You will create the perfect female.",
    linkPrimary: "",
  },
  {
    visible: true,
    image: "https://f4.bcbits.com/img/a3796973789_10.jpg",
    title: "SKIN",
    tagline: "You will create the perfect female.",
    linkPrimary: "",
  },
  {
    visible: true,
    image: "https://f4.bcbits.com/img/a3796973789_10.jpg",
    title: "SKIN",
    tagline: "You will create the perfect female.",
    linkPrimary: "",
  },
  {
    visible: true,
    image: "https://f4.bcbits.com/img/a3796973789_10.jpg",
    title: "SKIN",
    tagline: "You will create the perfect female.",
    linkPrimary: "",
  },
  {
    visible: true,
    image: "https://f4.bcbits.com/img/a3796973789_10.jpg",
    title: "SKIN",
    tagline: "You will create the perfect female.",
    linkPrimary: "",
  },
  {
    visible: true,
    image: "https://f4.bcbits.com/img/a3796973789_10.jpg",
    title: "SKIN",
    tagline: "You will create the perfect female.",
    linkPrimary: "",
  },
  {
    visible: true,
    image: "https://f4.bcbits.com/img/a3796973789_10.jpg",
    title: "SKIN",
    tagline: "You will create the perfect female.",
    linkPrimary: "",
  },
  {
    visible: true,
    image: "https://f4.bcbits.com/img/a3796973789_10.jpg",
    title: "SKIN",
    tagline: "You will create the perfect female.",
    linkPrimary: "",
  },
  {
    visible: true,
    image: "https://f4.bcbits.com/img/a3796973789_10.jpg",
    title: "SKIN",
    tagline: "You will create the perfect female.",
    linkPrimary: "",
  },
  {
    visible: true,
    image: "https://f4.bcbits.com/img/a3796973789_10.jpg",
    title: "SKIN",
    tagline: "You will create the perfect female.",
    linkPrimary: "",
  },
  {
    visible: true,
    image: "https://f4.bcbits.com/img/a3796973789_10.jpg",
    title: "SKIN",
    tagline: "You will create the perfect female.",
    linkPrimary: "",
  },
  {
    visible: true,
    image: "https://f4.bcbits.com/img/a3796973789_10.jpg",
    title: "SKIN",
    tagline: "You will create the perfect female.",
    linkPrimary: "",
  },
  {
    visible: true,
    image: "https://f4.bcbits.com/img/a3796973789_10.jpg",
    title: "SKIN",
    tagline: "You will create the perfect female.",
    linkPrimary: "",
  },
  {
    visible: true,
    image: "https://f4.bcbits.com/img/a3796973789_10.jpg",
    title: "SKIN",
    tagline: "You will create the perfect female.",
    linkPrimary: "",
  },
  {
    visible: true,
    image: "https://f4.bcbits.com/img/a3796973789_10.jpg",
    title: "SKIN",
    tagline: "You will create the perfect female.",
    linkPrimary: "",
  },
  {
    visible: true,
    image: "https://f4.bcbits.com/img/a3796973789_10.jpg",
    title: "SKIN",
    tagline: "You will create the perfect female.",
    linkPrimary: "",
  },
  {
    visible: true,
    image: "https://f4.bcbits.com/img/a3796973789_10.jpg",
    title: "SKIN",
    tagline: "You will create the perfect female.",
    linkPrimary: "",
  },
  {
    visible: true,
    image: "https://f4.bcbits.com/img/a3796973789_10.jpg",
    title: "SKIN",
    tagline: "You will create the perfect female.",
    linkPrimary: "",
  },
  {
    visible: true,
    image: "https://f4.bcbits.com/img/a3796973789_10.jpg",
    title: "SKIN",
    tagline: "You will create the perfect female.",
    linkPrimary: "",
  },
  {
    visible: true,
    image: "https://f4.bcbits.com/img/a3796973789_10.jpg",
    title: "SKIN",
    tagline: "You will create the perfect female.",
    linkPrimary: "",
  },
  {
    visible: true,
    image: "https://f4.bcbits.com/img/a3796973789_10.jpg",
    title: "SKIN",
    tagline: "You will create the perfect female.",
    linkPrimary: "",
  },
  {
    visible: true,
    image: "https://f4.bcbits.com/img/a3796973789_10.jpg",
    title: "SKIN",
    tagline: "You will create the perfect female.",
    linkPrimary: "",
  },
  {
    visible: true,
    image: "https://f4.bcbits.com/img/a3796973789_10.jpg",
    title: "SKIN",
    tagline: "You will create the perfect female.",
    linkPrimary: "",
  },
  {
    visible: true,
    image: "https://f4.bcbits.com/img/a3796973789_10.jpg",
    title: "SKIN",
    tagline: "You will create the perfect female.",
    linkPrimary: "",
  },
  {
    visible: true,
    image: "https://f4.bcbits.com/img/a3796973789_10.jpg",
    title: "SKIN",
    tagline: "You will create the perfect female.",
    linkPrimary: "",
  },
  {
    visible: true,
    image: "https://f4.bcbits.com/img/a3796973789_10.jpg",
    title: "SKIN",
    tagline: "You will create the perfect female.",
    linkPrimary: "",
  },
  {
    visible: true,
    image: "https://f4.bcbits.com/img/a3796973789_10.jpg",
    title: "SKIN",
    tagline: "You will create the perfect female.",
    linkPrimary: "",
  },
];

export default artDetails;
