import gameImages from "./gameImages";
import gameDescriptions from "./gameDescriptions";

const gameDetails = [
  {
    image: gameImages.subminimal.splashImage,
    title: "subMINIMAL",
    tagline: "A new state of unreality.",
    genre: "Arcade",
    description: gameDescriptions.subminimal,
    linkPrimary: "https://selfishdream.itch.io/subminimal/purchase",
    linkSecondary: "https://selfishdream.itch.io/subminimal",
    pageLink: "subminimal",
    screenshots: gameImages.subminimal.screenshots,
    video: "2oZRH_pU9MU",
  },
  {
    image: gameImages.fateless.splashImage,
    title: "Fateless",
    tagline: "The Garden is gone forever.",
    genre: "Platformer",
    description: gameDescriptions.fateless,
    linkPrimary: "https://selfishdream.itch.io/fateless/purchase",
    linkSecondary: "https://selfishdream.itch.io/fateless",
    pageLink: "fateless",
    screenshots: gameImages.fateless.screenshots,
    video: "2oZRH_pU9MU",
  },
  {
    image: gameImages.vessel.splashImage,
    title: "VESSEL: Faceless Eternities",
    tagline: "Your fate is sealed.",
    genre: "Shooter",
    description: gameDescriptions.vessel,
    linkPrimary: "https://selfishdream.itch.io/vessel/purchase",
    linkSecondary: "https://selfishdream.itch.io/vessel",
    pageLink: "vessel",
    screenshots: gameImages.vessel.screenshots,
    video: "2oZRH_pU9MU",
  },
  {
    image: gameImages.theFleshOfFallenAngels.splashImage,
    title: "The Flesh of Fallen Angels",
    tagline: "Nothing is sacred.",
    genre: "Role Playing",
    description: gameDescriptions.theFleshOfFallenAngels,
    linkPrimary:
      "https://selfishdream.itch.io/the-flesh-of-fallen-angels/purchase",
    linkSecondary: "https://selfishdream.itch.io/the-flesh-of-fallen-angels",
    pageLink: "the-flesh-of-fallen-angels",
    screenshots: gameImages.theFleshOfFallenAngels.screenshots,
    video: "2oZRH_pU9MU",
  },
  {
    image: gameImages.isntLifeDisappointing.splashImage,
    title: "Isn't Life Disappointing?",
    tagline: "The burden of pain.",
    genre: "Adventure",
    description: gameDescriptions.isntLifeDisappointing,
    linkPrimary: "https://selfishdream.itch.io/isntlifedisappointing/purchase",
    linkSecondary: "https://selfishdream.itch.io/isntlifedisappointing",
    pageLink: "isnt-life-disappointing",
    screenshots: gameImages.isntLifeDisappointing.screenshots,
    video: "2oZRH_pU9MU",
  },
  {
    image: gameImages.suffer.splashImage,
    title: "S U F F E R",
    tagline: "Do you have any regrets?",
    genre: "Adventure",
    description: gameDescriptions.suffer,
    linkPrimary: "https://selfishdream.itch.io/suffer/purchase",
    linkSecondary: "https://selfishdream.itch.io/suffer",
    pageLink: "suffer",
    screenshots: gameImages.suffer.screenshots,
    video: "G6Cw5B98wmg",
  },
  {
    image: gameImages.soul.splashImage,
    title: "SOUL: A Voiceless Decay",
    tagline: "The fear of death.",
    genre: "Adventure",
    description: gameDescriptions.soul,
    linkPrimary: "https://selfishdream.itch.io/soul/purchase",
    linkSecondary: "https://selfishdream.itch.io/soul",
    pageLink: "soul",
    screenshots: gameImages.soul.screenshots,
    video: "3uRcoBTnSHA",
  },
  {
    image: gameImages.suicide.splashImage,
    title: "I Want to Blow My Brains Out",
    tagline: "Pull the trigger.",
    genre: "Experimental",
    description: gameDescriptions.suicide,
    linkPrimary: "https://selfishdream.itch.io/suicide/purchase",
    linkSecondary: "https://selfishdream.itch.io/suicide",
    pageLink: "suicide",
    screenshots: gameImages.suicide.screenshots,
    video: "7T3X2mq_xPQ",
  },
  {
    image: gameImages.sheIsAllYours.splashImage,
    title: "She Is All Yours",
    tagline: "Do what you want.",
    genre: "Point & Click",
    description: gameDescriptions.sheIsAllYours,
    linkPrimary: "https://selfishdream.itch.io/she-is-all-yours/purchase",
    linkSecondary: "https://selfishdream.itch.io/she-is-all-yours",
    pageLink: "she-is-all-yours",
    screenshots: gameImages.sheIsAllYours.screenshots,
    video: "2oZRH_pU9MU",
  },
  {
    image: gameImages.personal.splashImage,
    title: "There is a dark voice inside my mind.",
    tagline: "Something personal.",
    genre: "Experimental",
    description: gameDescriptions.personal,
    linkPrimary: "https://selfishdream.itch.io/personal/purchase",
    linkSecondary: "https://selfishdream.itch.io/personal",
    pageLink: "personal",
    screenshots: gameImages.personal.screenshots,
    video: "i0taLJFEg6M",
  },
  {
    image: gameImages.skin.splashImage,
    title: "SKIN",
    tagline: "You will create perfection.",
    genre: "Adventure",
    description: gameDescriptions.skin,
    linkPrimary: "https://selfishdream.itch.io/skin/purchase",
    linkSecondary: "https://selfishdream.itch.io/skin",
    pageLink: "skin",
    screenshots: gameImages.skin.screenshots,
    video: "Awl2TKZtIkA",
  },
];

export { gameDetails };
export default gameDetails;
