import {
  tenebris1,
  tenebris2,
  tenebris3,
  tenebris4,
  tenebris5,
  tenebris6,
  tenebris7,
  tenebris8,
  within1,
  within2,
  within3,
  within4,
  within5,
  within6,
  within7,
  subminimal1,
  subminimal2,
  subminimal3,
  subminimal4,
  subminimal5,
  fateless1,
  fateless2,
  fateless3,
  fateless4,
  fateless5,
  fateless6,
  fateless7,
  fateless8,
  fateless9,
  vessel1,
  vessel2,
  vessel3,
  vessel4,
  vessel5,
  theFleshOfFallenAngels1,
  theFleshOfFallenAngels2,
  theFleshOfFallenAngels3,
  theFleshOfFallenAngels4,
  theFleshOfFallenAngels5,
  theFleshOfFallenAngels6,
  theFleshOfFallenAngels7,
  isntLifeDisappointing1,
  isntLifeDisappointing2,
  isntLifeDisappointing3,
  isntLifeDisappointing4,
  isntLifeDisappointing5,
  isntLifeDisappointing6,
  isntLifeDisappointing7,
  isntLifeDisappointing8,
  isntLifeDisappointing9,
  isntLifeDisappointing10,
  suffer1,
  suffer2,
  suffer3,
  suffer4,
  suffer5,
  suffer6,
  soul1,
  soul2,
  soul3,
  soul4,
  soul5,
  suicide1,
  suicide2,
  suicide3,
  suicide4,
  sheIsAllYours1,
  sheIsAllYours2,
  sheIsAllYours3,
  sheIsAllYours4,
  sheIsAllYours5,
  sheIsAllYours6,
  personal1,
  personal2,
  personal3,
  personal4,
  personal5,
  skin1,
  skin2,
  skin3,
  skin4,
  skin5,
  skin6,
} from "../images";

const gameMedia = {
  tenebris: {
    splashImage: tenebris6,
    screenshots: [
      tenebris1,
      tenebris2,
      tenebris3,
      tenebris4,
      tenebris5,
      tenebris6,
      tenebris7,
      tenebris8,
    ],
    video: "",
  },
  within: {
    splashImage: within6,
    screenshots: [
      within1,
      within2,
      within3,
      within4,
      within5,
      within6,
      within7,
    ],
    video: "I0hsJc3nVUA",
  },
  subminimal: {
    splashImage: subminimal2,
    screenshots: [
      subminimal1,
      subminimal2,
      subminimal3,
      subminimal4,
      subminimal5,
    ],
    video: "",
  },
  fateless: {
    splashImage: fateless8,
    screenshots: [
      fateless1,
      fateless2,
      fateless3,
      fateless4,
      fateless5,
      fateless6,
      fateless7,
      fateless8,
      fateless9,
    ],
    video: "2oZRH_pU9MU",
  },
  vessel: {
    splashImage: vessel3,
    screenshots: [vessel1, vessel2, vessel3, vessel4, vessel5],
    video: "IRNyZAu5Fj4",
  },
  theFleshOfFallenAngels: {
    splashImage: theFleshOfFallenAngels1,
    screenshots: [
      theFleshOfFallenAngels1,
      theFleshOfFallenAngels2,
      theFleshOfFallenAngels3,
      theFleshOfFallenAngels4,
      theFleshOfFallenAngels5,
      theFleshOfFallenAngels6,
      theFleshOfFallenAngels7,
    ],
    video: "InN0L1UC4zM",
  },
  isntLifeDisappointing: {
    splashImage: isntLifeDisappointing10,
    screenshots: [
      isntLifeDisappointing1,
      isntLifeDisappointing2,
      isntLifeDisappointing3,
      isntLifeDisappointing4,
      isntLifeDisappointing5,
      isntLifeDisappointing6,
      isntLifeDisappointing7,
      isntLifeDisappointing8,
      isntLifeDisappointing9,
      isntLifeDisappointing10,
    ],
    video: "ZEQKm92IPfw",
  },
  suffer: {
    splashImage: suffer6,
    screenshots: [suffer1, suffer2, suffer3, suffer4, suffer5, suffer6],
    video: "G6Cw5B98wmg",
  },
  soul: {
    splashImage: soul1,
    screenshots: [soul1, soul2, soul3, soul4, soul5],
    video: "3uRcoBTnSHA",
  },
  suicide: {
    splashImage: suicide1,
    screenshots: [suicide1, suicide2, suicide3, suicide4],
    video: "7T3X2mq_xPQ",
  },
  sheIsAllYours: {
    splashImage: sheIsAllYours2,
    screenshots: [
      sheIsAllYours1,
      sheIsAllYours2,
      sheIsAllYours3,
      sheIsAllYours4,
      sheIsAllYours5,
      sheIsAllYours6,
    ],
    video: "JrTJU1yqVPs",
  },
  personal: {
    splashImage: personal1,
    screenshots: [personal1, personal2, personal3, personal4, personal5],
    video: "i0taLJFEg6M",
  },
  skin: {
    splashImage: skin1,
    screenshots: [skin1, skin2, skin3, skin4, skin5, skin6],
    video: "Awl2TKZtIkA",
  },
};

export { gameMedia };
export default gameMedia;
